run:
  timeout: 5m
  tests: true
  issues.exclude-dirs:
    - dist
    - vendor
  issues.exclude-files:
    - ".*_test.go"

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - gocyclo
    - dupl
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - dupl
      text: "generated"

linters-settings:
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goimports:
    local-prefixes: github.com/gallyamow/go-duplicated-files-finder
